#!/bin/bash

#don't change filename with .sh extension
#order matters

if [[ -e /home/parman/.parmanode/parmanode.conf ]] ; then
if grep -q "rp_count" < /home/parman/.parmanode/parmanode.conf ; then exit ; fi
fi

#always get latest version of parmanode
cd $HOME/parman_programs/parmanode && git config pull.rebase false >/dev/null 2>&1 && git pull >/dev/null 2>&1

