SocksPort 0.0.0.0:9060
ControlPort 9061
CookieAuthentication 1
CookieAuthFileGroupReadable 1
DataDirectoryGroupReadable 1
HiddenServiceDir /var/lib/tor/electrs-service/
HiddenServicePort 7004 0.0.0.0:50005