version: "3.7"

services:
  web:
    api:
    environment:
      MEMPOOL_BACKEND: "electrum"

    environment:
      FRONTEND_HTTP_PORT: "8080"
      BACKEND_MAINNET_HTTP_HOST: "api"
    image: mempool/frontend:latest
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    command: "./wait-for db:3306 --timeout=720 -- nginx -g 'daemon off;'"
    ports:
      - 80:8080
  api:
    environment:
      MEMPOOL_BACKEND: "none" #or "electrum"
      CORE_RPC_HOST: "host.docker.internal"
      CORE_RPC_PORT: "8332"
      ELECTRUM_HOST: "host.docker.internal"
      ELECTRUM_PORT: "50001"
      ELECTRUM_TLS_ENABLED: "true"
      CORE_RPC_USERNAME: "$rpcuser"
      CORE_RPC_PASSWORD: "$rpcpass"
      DATABASE_ENABLED: "true"
      DATABASE_HOST: "db"
      DATABASE_DATABASE: "mempool"
      DATABASE_USERNAME: "mempool"
      DATABASE_PASSWORD: "mempool"
      STATISTICS_ENABLED: "true"
    image: mempool/backend:latest
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    command: "./wait-for-it.sh db:3306 --timeout=720 --strict -- ./start.sh"
    volumes:
      - ./data:/backend/cache
  db:
    environment:
      MYSQL_DATABASE: "mempool"
      MYSQL_USER: "mempool"
      MYSQL_PASSWORD: "mempool"
      MYSQL_ROOT_PASSWORD: "admin"
    image: mariadb:10.5.21
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ./mysql/data:/var/lib/mysql