FROM debian:bullseye-slim
ENV DEBIAN_FRONTEND=noninteractive

#Joinmarket
RUN mkdir -p /jm/clientserver
WORKDIR /jm/clientserver

RUN apt-get update -y
RUN apt-get install -y --no-install-recommends \
                   wget gnupg sudo procps vim nano curl git ca-certificates
RUN apt-get install -y --no-install-recommends \
                   python3-venv curl python3-dev python3-pip build-essential automake
RUN apt-get install -y --no-install-recommends \
                   pkg-config libtool libgmp-dev libltdl-dev libssl-dev libatlas3-base libopenjp2-7
RUN apt-get install -y --no-install-recommends \
                   less tmux socat net-tools tor

COPY . .

RUN pip3 install 'wheel>=0.35.1' 
RUN pip install matplotlib
RUN ./install.sh --docker-install --without-qt 
RUN rm -rf /var/lib/apt/lists/*

COPY Dockerfile_torrc /etc/tor/torrc
COPY Dockerfile_torsocks.conf /etc/tor/torsocks.conf

WORKDIR /jm/clientserver/scripts
CMD ["/bin/sh", "-c", "tor && python3 /jm/clientserver/scripts/joinmarketd.py"]
