function orderbook_access_info {

set_terminal ; echo -e "
########################################################################################

    The order book is a bit like the Bitcoin mempool. JoinMarket users each keep their
    own copy of the coinjoin offers, and share them between other users. Not every
    copy is going to be identical.

    Sometimes there are connection issues over the Tor Network and your list might
    not look complete. Refreshing can help.

    Your orderbook can be accessed from the URLs provided in the main JoinMarket menu.

    An althernative to a self-hosted order book is to use a public one. Here's one
    example you could use:
$bright_blue
    https://nixbitcoin.org/orderbook/
$orange
    To see your offer listed in the order book, you first need to find your nickname,
    a randomly generated string generated by JoinMarket. It'll be in the 
    Yield Generator Menu.

########################################################################################
"
enter_continue ; jump $enter_cont

}