#!/bin/bash

# Parmaview helper function
# Usage:
#    sudo /usr/local/parmanode/p4run "screened argument allowed only here"
# Location
# $pn/restricted --> /usr/local/parmanode/p4run (live)


#variables
local xsudo=sudo
dn=/dev/null
torrc=/etc/tor/torrc
varlibtor=/var/lib/tor
USER=$(cat /usr/local/parmanode/USER) ; HOME=/home/$USER
dp=$HOME/.parmanode/
bc=$HOME/.bitcoin/bitcoin.conf
pvlog=$dp/parmaview/parmaview.log
p4run=1

case "$1" in

"add_bitcoin_hidden_service")

    if ! sudo grep "HiddenServiceDir $varlibtor/bitcoin-service/" $torrc | grep -v "^#" >$dn 2>&1 ; then 
        echo "HiddenServiceDir $varlibtor/bitcoin-service/" | sudo tee -a $torrc >$dn 2>&1
    fi

    if ! sudo grep "HiddenServicePort 8333 127.0.0.1:8333" $torrc | grep -v "^#" >$dn 2>&1 ; then 
        echo "HiddenServicePort 8333 127.0.0.1:8333" | sudo tee -a $torrc >$dn 2>&1
        systemctl restart tor #necessary as the service is new now
    fi
;;

"get_onion_address_variable")

    if [[ "$2" == "bitcoin" ]] ; then
    export ONION_ADDR="$(sudo cat $varlibtor/bitcoin-service/hostname 2>$dn)"
    fi
;;

"bitcoin_binary_symlinks")
    sudo mkdir -p /usr/local/bin/parmanode/
    sudo ln -s  /usr/local/bin/parmanode/bitcoin-cli /usr/local/bin/bitcoin-cli >$dn 2>&1
    sudo ln -s  /usr/local/bin/parmanode/bitcoind /usr/local/bin/bitcoind >$dn 2>&1
    sudo ln -s  /usr/local/bin/parmanode/bitcoin-qt /usr/local/bin/bitcoin-qt >$dn 2>&1
    sudo ln -s  /usr/local/bin/parmanode/bitcoin-tx /usr/local/bin/bitcoin-tx >$dn 2>&1
    sudo ln -s  /usr/local/bin/parmanode/bitcoin-util /usr/local/bin/bitcoin-util >$dn 2>&1
    sudo ln -s  /usr/local/bin/parmanode/bitcoin-wallet /usr/local/bin/bitcoin-wallet >$dn 2>&1
    sudo ln -s  /usr/local/bin/parmanode/test_bitcoin /usr/local/bin/test_bitcoin >$dn 2>&1
;;

"bitcoin_service_file")
    sudo mv "$2" /etc/systemd/system/bitcoind.service 
;;

sudomakeinstallbitcoingithub)
cd $HOME/parmanode/bitcoin_github
sudo make install
;;

move_bitcoin_binaries)
    sudo mv /usr/local/bin/*bitcoin* /usr/local/bin/parmanode/ >$dn 2>&1
;;  

bitcoin_ninja_install)
sudo ninja install >$dn 2>&1
;;

bitcoin_compile_dependencies)
sudo apt-get install -y make 2>>$pvlog              
sudo apt-get install -y automake 2>>$pvlog              
sudo apt-get install -y cmake 2>>$pvlog                                     
sudo apt-get install -y curl 2>>$pvlog                                      
sudo apt-get install -y g++-multilib 2>>$pvlog                              
sudo apt-get install -y libtool 2>>$pvlog                                   
sudo apt-get install -y binutils 2>>$pvlog                                  
sudo apt-get install -y bsdmainutils 2>>$pvlog                              
sudo apt-get install -y build-essential 2>>$pvlog                           
sudo apt-get install -y autotools-dev 2>>$pvlog                             
sudo apt-get install -y pkg-config 2>>$pvlog                                
sudo apt-get install -y ninja-build 2>>$pvlog                               
sudo apt-get install -y python3 2>>$pvlog                                   
sudo apt-get install -y patch 2>>$pvlog                                     
sudo apt-get install -y autoconf 2>>$pvlog                                  
sudo apt-get install -y libboost-all-dev 2>>$pvlog                          
sudo apt-get install -y imagemagick 2>>$pvlog                               
sudo apt-get install -y librsvg2-bin 2>>$pvlog                              
sudo apt-get install -y libdb-dev 2>>$pvlog                                 
sudo apt-get install -y libdb++-dev 2>>$pvlog                               
sudo apt-get install -y libzmq3-dev 2>>$pvlog                               
sudo apt-get install -y libqrencode-dev 2>>$pvlog                           
sudo apt-get install -y libsqlite3-dev 2>>$pvlog                            
sudo apt-get install -y libevent-dev 2>>$pvlog                              
sudo apt-get install -y libssl-dev 2>>$pvlog                                
sudo apt-get install -y libminiupnpc-dev 2>>$pvlog                          
sudo apt-get install -y libprotobuf-dev 2>>$pvlog                           
sudo apt-get install -y protobuf-compiler 2>>$pvlog                        
echo -e "\nnon-GUI section ran for bitcoin_compile_dependencies\n" >>$pvlog
if [[ $2 == "GUI" ]] ; then
sudo apt-get install -y qtchooser 2>>$pvlog   
sudo apt-get install -y qtbase5-dev-tools 2>>$pvlog  
sudo apt-get install -y qtcreator 2>>$pvlog 
sudo apt-get install -y qtbase5-dev 2>>$pvlog 
sudo apt-get install -y qt5-qmake  2>>$pvlog 
sudo apt-get install -y qttools5-dev-tools 2>>$pvlog
sudo apt-get install -y qt5-default 2>>$pvlog 
sudo apt-get install -y qtchooser  2>>$pvlog 
sudo apt-get install -y libqt5gui5 2>>$pvlog 
sudo apt-get install -y libqt5core5a  2>>$pvlog 
sudo apt-get install -y libqt5dbus5  2>>$pvlog 
sudo apt-get install -y qttools5-dev  2>>$pvlog  
sudo apt-get install -y libqt5widgets5  2>>$pvlog  
echo -e "\nGUI section ran for bitcoin_compile_dependencies\n" >>$pvlog
fi
return 0
;;
chownparmanode)
sudo chown -R $USER /media/$USER/parmanode 2>>$pvlog
;;    

remove_bitcoin_directories)
sudo rm -rf $HOME/parmanode/bitcoin >$dn 2>>$pvlog
sudo rm -rf $HOME/parmanode/bitcoin_github >$dn 2>>$pvlog
sudo rm -rf $HOME/parmanode/bitcoinknots_github >$dn 2>>$pvlog
echo "RUNNING sudo rm -rf /usr/local/bin/*bitcoin*" >>$pvlog
echo "HOME is $HOME" >>$pvlog
sudo rm -rf /usr/local/bin/*bitcoin* >$dn 2>>$pvlog
;;

esac
