#!/bin/bash

# Parmaview helper function
# Usage:
#    sudo /usr/local/parmanode/p4run "screened argument allowed only here"
# Location
# $pn/restricted --> /usr/local/parmanode/p4run (live)


#variables
dn=/dev/null
torrc=/etc/tor/torrc
varlibtor=/var/lib/tor


#find HOME variable.
source /usr/local/parmanode/src/home.sh

dp=$HOME/.parmanode/
bc=$HOME/.bitcoin/bitcoin.conf

case "$1" in

"add_bitcoin_hidden_service")

    if ! grep "HiddenServiceDir $varlibtor/bitcoin-service/" $torrc | grep -v "^#" >$dn 2>&1 ; then 
        echo "HiddenServiceDir $varlibtor/bitcoin-service/" | tee -a $torrc >$dn 2>&1
    fi

    if ! grep "HiddenServicePort 8333 127.0.0.1:8333" $torrc | grep -v "^#" >$dn 2>&1 ; then 
        echo "HiddenServicePort 8333 127.0.0.1:8333" | tee -a $torrc >$dn 2>&1
        systemctl restart tor #necessary as the service is new now
    fi
;;

"get_onion_address_variable")
    #necessary to call the script with an assignment to ONION_ADDR
    if [[ "$2" == "bitcoin" ]] ; then
    cat $varlibtor/bitcoin-service/hostname 2>$dn
    fi
;;

"bitcoin_binary_symlinks")
    mkdir -p /usr/local/bin/parmanode/
    ln -s  /usr/local/bin/parmanode/bitcoin-cli /usr/local/bin/bitcoin-cli >$dn 2>&1
    ln -s  /usr/local/bin/parmanode/bitcoind /usr/local/bin/bitcoind >$dn 2>&1
    ln -s  /usr/local/bin/parmanode/bitcoin-qt /usr/local/bin/bitcoin-qt >$dn 2>&1
    ln -s  /usr/local/bin/parmanode/bitcoin-tx /usr/local/bin/bitcoin-tx >$dn 2>&1
    ln -s  /usr/local/bin/parmanode/bitcoin-util /usr/local/bin/bitcoin-util >$dn 2>&1
    ln -s  /usr/local/bin/parmanode/bitcoin-wallet /usr/local/bin/bitcoin-wallet >$dn 2>&1
    ln -s  /usr/local/bin/parmanode/test-bitcoin /usr/local/bin/test-bitcoin >$dn 2>&1
;;

"delete_bitcoin_files")
    rm -rf /usr/local/bin/*bitcoin*
;;

"bitcoin_compile_dependency_script")
    /usr/local/parmanode/scripts/bitcoin_compile_dependency_script.sh
;;
"compile_bitcoin")
    /usr/local/parmanode/scripts/compile_bitcoin.sh
;;
"move_bitcoind_service_file")
    cp -r /usr/local/parmanode/service/bitcoind.service /etc/systemd/system/bitcoind.service
;;
"move_btcpay_service_file")
    cp -r /usr/local/parmanode/service/btcpay.service /etc/systemd/system/btcpay.service
;;
"move_electrs_service_file")
    cp -r /usr/local/parmanode/service/electrs.service /etc/systemd/system/electrs.service
;;
"move_fulcrum_service_file")
    cp -r /usr/local/parmanode/service/fulcrum.service /etc/systemd/system/fulcrum.service
;;
"move_electrumx_service_file")
    cp -r /usr/local/parmanode/service/electrumx.service /etc/systemd/system/electrumx.service
;;
"install_tor")
    if [[ $(uname) == "Linux" ]] ; then sudo apt-get install tor -y  ; fi
;;
"bitcoin_tor"|"tor")
    /usr/local/parmanode/scripts/tor.sh "$2" "$3"
;;
"rpcbind")
[[ -e $bc ]] && ! grep -q "rpcbind=0.0.0.0" $bc >$dn 2>&1 && echo "rpcbind=0.0.0.0" | tee -a $bc >$dn 2>&1
;;

"unmount")
   /usr/local/parmanode/scripts/drives.sh "unmount"
;;

esac
